### ISSUE TITLE
[submission] FOSDEM 2019 talks about Racket

### ISSUE THREAD

**Issue by gregid** [racket-news/racket-news.github.io-src#1]
Once recordings will be available on [Youtube](https://www.youtube.com/user/fosdemtalks/videos), links to them should be included in the next newsletter
The talks I could find on https://fosdem.org/2019/schedule/track/minimalistic_languages/ are
* ["Why JSON when you can DSL? Your problematics deserve their own language"](https://fosdem.org/2019/schedule/event/jsonwhendsl/) by Jérôme Martin
* ["A Guiler's Year of Racket"](https://fosdem.org/2019/schedule/event/guileracket/) by Christopher Webber
* ["Fractalide and Cantor A Racket application built with Flow-Based Programming"](https://fosdem.org/2019/schedule/event/fractalideandcantor/) by Claes Wallin
* ["Make your own language with Racket. A kickstart workshop for the creative minds"](https://fosdem.org/2019/schedule/event/makeownlangracket/) by Jérôme Martin

**Comment by pmatos** [comment]
Thanks, will add it to issue 2. Which name should I attribute this to - otherwise will use just `gregid`.
