### ISSUE TITLE
PEG release

### ISSUE THREAD

**Issue by rain-1** [racket-news/racket-news.github.io-src#5]
Could we notify version 0.3 of the PEG parser library is released in the next issue?

https://docs.racket-lang.org/peg/index.html

It can be installed through the racket pkgs system.

**Comment by pmatos** [comment]
Thanks, marked for issue 3. How should I acknowledge you in contributions? Name or github username?

**Comment by rain-1** [comment]
github username

**Comment by pmatos** [comment]
Coming out in issue 3 tomorrow. Thanks.
